spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spawn_prod
    username: spawn_prod_user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    show-sql: false